### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by xhacker** [jesseXu/Bang#1]
Is this project open-sourced?

Thanks.

**Comment by jesseXu** [comment]
Yeah, I will attach MIT License to the project.

Go ahead.

On Sun, Apr 20, 2014 at 1:51 PM, xhacker notifications@github.com wrote:

> Is this project open-sourced?
> 
> Thanks.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jesseXu/Bang/issues/1
> .

## 

Cell：+86 186 5797 8885
 Email：jessse0628@gmail.com
QQ：352605909

**Comment by xhacker** [comment]
Cool!
:smile:
