### ISSUE TITLE
asdfasd?

### ISSUE THREAD

**Issue by zhuangya** [jesseXu/Bang#2]
there is a `asdfasd` before login in =/

maybe replace this with `Bang!` or something else??

![image](https://cloud.githubusercontent.com/assets/499038/2780270/6881c9fa-cb05-11e3-9505-d7fe0665bae8.png)

**Comment by jesseXu** [comment]
OK. Thanks, I will. I also have plan to make the login view more elegant.

On Thu, Apr 24, 2014 at 12:37 AM, Ya Zhuang notifications@github.comwrote:

> there is a asdfasd before login in =/
> 
> maybe replace this with Bang! or something else??
> 
> [image: image]https://cloud.githubusercontent.com/assets/499038/2780270/6881c9fa-cb05-11e3-9505-d7fe0665bae8.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jesseXu/Bang/issues/2
> .

## 

Cell：+86 186 5797 8885
 Email：jessse0628@gmail.com
QQ：352605909
